### ISSUE TITLE
Q: Can I make REPL window scroll down automatically on startup?

### ISSUE THREAD

**Issue by aca** [axvr/zepl.vim#7]
Hi, thanks for the great plugin. Simple, works in vim-way, I love it.

I have some questions with the scrolling of the repl window.

![image](https://user-images.githubusercontent.com/50316549/119828460-24698880-bf35-11eb-995e-0ec4938a1136.png)

In the picture, output is long and the repl window doesn't scrolled down on startup. When I go to the repl window and position my cursor at the end of the buffer, it gets scrolled down automatically. 
Is there a way to position cursor on the bottom of the repl buffer on startup?

**Comment by axvr** [comment]
Hi, I've [pushed](https://github.com/axvr/zepl.vim/commit/4c8ada5d448f9a2b7ccfb8263a29beac7ae21f3c) a contrib module which contains a (hacky) workaround for the problem.

Just update Zepl and add this line to your `init.vim` file to enable the "fix".

```vim
runtime zepl/contrib/nvim_autoscroll_hack.vim
```

Let me know if it still isn't working for you.

---

The problem was that Neovim's `:terminal` (which Zepl uses) only auto-scrolls when your cursor is on the last line of the buffer.  The workaround I pushed will remap `<C-\><C-n>` to also move the cursor to the bottom.

Related: https://github.com/neovim/neovim/issues/2636
